version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mirdb_v2
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      DATABASE_HOST: db
  web:
    build: ./web
    volumes:
      - ./web:/var/www/app
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mirdb_v2
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    command: sh -c "npm i && npm run serve:dev"